---
driver:
  name: vagrant
  ssh:
    insert_key: false

provisioner:
  name: chef_zero
  chef_zero_port: 9010
  encrypted_data_bag_secret_key_path: './fixtures/secrets/fakey-mcfakerton'
  data_bags_path: './fixtures/data_bags'

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.2
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: chef-server
    run_list:
      - recipe[ntp]
      - recipe[stack::hostsfile]
      - recipe[stack::setup_ssh_keys]
      - recipe[stack::chef-server]
    driver:
      vm_hostname: chef.services.com
      network:
        - ['private_network', {ip: '33.33.33.10'}]
      customize:
        memory: 2048
        cpus: 2
    attributes:

  - name: automate
    run_list:
      - recipe[ntp]
      - recipe[stack::hostsfile]
      - recipe[stack::delivery_keys]
      - recipe[stack::delivery]
      - recipe[stack::create_enterprise]
      - recipe[stack::delivery_node]
    attributes:
      delivery:
        fqdn: 'automate.services.com'
        chef_server: https://chef.services.com/organizations/delivery
        insights:
          enable: true
    driver:
      vm_hostname: automate.services.com
      network:
        - ['private_network', {ip: '33.33.33.11'}]
      customize:
        memory: 1024
        cpus: 1

  - name: build
    run_list:
      - recipe[ntp]
      - recipe[stack::hostsfile]
      - recipe[stack::delivery_keys]
      - recipe[stack::build_node]
    attributes:
    driver:
      vm_hostname: build.services.com
      network:
        - ['private_network', {ip: '33.33.33.12'}]
      customize:
        memory: 1024
        cpus: 1

  - name: supermarket
    run_list:
      - recipe[ntp]
      - recipe[stack::hostsfile]
      - recipe[stack::setup_ssh_keys]
      - recipe[stack::supermarket]
    attributes:
      supermarket_omnibus:
        chef_server_url: 'https://chef.services.com'
        chef_oauth2_verify_ssl: false
    driver:
      vm_hostname: supermarket.services.com
      network:
        - ['private_network', {ip: '33.33.33.13'}]
      customize:
        memory: 1024
        cpus: 1

  - name: compliance
    run_list:
      - recipe[ntp]
      - recipe[stack::hostsfile]
      - recipe[stack::compliance]
    attributes:
      compliance:
        accept_license: true
        fqdn: compliance.services.com
    driver:
      vm_hostname: compliance.services.com
      network:
        - ['private_network', {ip: '33.33.33.14'}]
      customize:
        memory: 1024
        cpus: 1
