---
driver:
  name: vagrant
  #uncomment synched_folders to transfer this cookbook to the /tmp/data directory
  #synced_folders:
  #    - [<%= File.join(ENV['PWD'])%>, '/tmp/data']
  
  ssh:
    insert_key: false

provisioner:
  name: chef_zero
  chef_zero_port: 9010

platforms:
  - name: centos-6.6

suites:
  - name: chef-server
    run_list:
      - recipe[test::hostsfile]
      - recipe[test::setup_ssh_keys]
      - recipe[chef-server::default]
      - recipe[chef-server::addons]
      - recipe[test::example_org_and_user]
      - recipe[test::delivery_setup]
    driver:
      vm_hostname: chef.example.com
      network:
        - ['private_network', {ip: '33.33.33.10'}]
      customize:
        memory: 2048
        cpus: 2
    attributes:
      chef-server:
        api_fqdn: 'chef.example.com'
        addons:
          - opscode-manage
          - opscode-reporting
          - opscode-push-jobs-server
        configuration:
          oc_id:
            vip: localhost # workaround for chef version <=12.1.2 expected to be fixed in >12.1.2
            applications:
              analytics:
                redirect_uri: 'https://analytics.example.com/'
              supermarket:
                redirect_uri: 'https://supermarket.example.com/auth/chef_oauth2/callback'
          rabbitmq:
            vip: '33.33.33.10'
            node_ip_address: '0.0.0.0'

  - name: analytics
    run_list:
      - recipe[test::hostsfile]
      - recipe[test::replicate_opscode_analytics]
      - recipe[chef-analytics::default]
    attributes:
    # uncomment this to install from package_source where
    # 1. You've uncommented the synched_folders in lines ~5&6
    # 2. You've copied the package to the root of chef-services
    # 3. You've updated the version and package_source values below
    #  chef-analytics:
    #    version: '1.1.6-beta.0'
    #    package_source: '/tmp/data/opscode-analytics-1.1.6-beta.0.rpm'
    driver:
      vm_hostname: analytics.example.com
      network:
        - ['private_network', {ip: '33.33.33.11'}]
      customize:
        memory: 1024
        cpus: 1

  # - name: delivery
  #   run_list:
  #     - recipe[test::hostsfile]
  #     - recipe[test::delivery_keys]
  #     - recipe[delivery-cluster::delivery]
  #     - recipe[test::create_enterprise]
  #   attributes:
  #     delivery-cluster:
  #       delivery:
  #         fqdn: 'delivery.example.com'
  #         chef_server: https://chef.example.com/organizations/chef_delivery
  #   driver:
  #     vm_hostname: delivery.example.com
  #     network:
  #       - ['private_network', {ip: '33.33.33.12'}]
  #     customize:
  #       memory: 1024
  #       cpus: 1

  - name: supermarket
    run_list:
      - recipe[test::hostsfile]
      - recipe[test::setup_ssh_keys]
      - recipe[supermarket-omnibus-cookbook::default]
      - recipe[test::supermarket_oc_id]
    attributes:
      supermarket_omnibus:
        chef_server_url: 'https://chef.example.com'
        chef_oauth2_verify_ssl: false
    driver:
      vm_hostname: supermarket.example.com
      network:
        - ['private_network', {ip: '33.33.33.13'}]
      customize:
        memory: 1024
        cpus: 1
