name             'chef-services'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures chef-services'
long_description 'Installs/Configures chef-services'
version          '1.5.0'

depends 'yum'
depends 'apt'
depends 'chef-analytics'
depends 'supermarket-omnibus-cookbook'
depends 'delivery-cluster'
