default['delivery']['version'] = 'latest'
default['delivery']['chef_server'] = 'https://chef.services.com/organizations/delivery'
default['chef_server']['fqdn'] = nil
default['compliance']['version'] = 'latest'
default['compliance']['package_source'] = nil
default['compliance']['channel'] = :stable
default['compliance']['accept_license'] = false
default['chef_automate']['fqdn'] = 'automate.services.com'
default['chefdk']['bashrc'] = '/etc/bashrc'
default['chefdk']['version'] = 'latest'
default['chefdk']['source'] = "http://omnitruck.chef.io/stable/chefdk/download?p=#{node['platform']}&pv=#{node['platform_version']}&m=#{node['kernel']['processor']}&v=latest"
